### PR TITLE
Test for RowsColumnsScanner

### PR DESCRIPTION
**Pull request by bitpossum**
also:
 - swapped the argument order on ScanColumn to conform with the accepted proposal
 - changed the variable name in Rows.Scan to 'rcs'

### CODE REVIEW

**Comment by bitpossum** [comment]
Hi @jackc.

I have created a test and made the requested changes.
Maybe you could have a look and submit it to gerrit?
(I have never created a PR before - sorry if I made a mistake.)

**Comment by jackc** [comment]
It's my first time submitting a change to Go as well. Also, not sure if or how the PR to a fork will work with the link to Gerritt. 

But the more important question is have you done the CLA for the Go project? The Go project won't accept any code without it.

**Comment by bitpossum** [comment]
No, I don't have a CLA. I just want to help your change to go over the finish line, because I could use this feature with my hobby database driver.
Instead of merging this PR, maybe you cold just copy the relevant lines to your code and submit a new patch ?
I think this way my user will never show up anywhere in Git history or in the Go project.

**Comment by jackc** [comment]
Thanks. To ensure there were no CLA issues I rewrote the test, but this PR was very helpful to point me in the correct direction.

**Pull request closed without merging**
